name: nacl_win
description: A flutter plugin for Windows for generating Ed25519 keys and signing messages.
version: 0.0.4
homepage: https://github.com/THCLab/nacl_win

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  ffi: ^2.0.1
  flutter:
    sdk: flutter
  flutter_rust_bridge: 1.54.1
  meta: ^1.8.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  ffigen: ^6.0.1

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: NaclWinPluginCApi
